name: Flutter Linux AppImage Release

on:
  push:
    tags:
      - 'v*'

# Add write permissions for releases
permissions:
  contents: write

jobs:
  build-linux-appimage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to get tag info

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libblkid-dev \
            liblzma-dev \
            cmake \
            ninja-build \
            pkg-config \
            clang \
            gcc \
            git \
            libfuse2
          flutter pub get

      - name: Build Linux AppImage
        run: |
          # Build the Flutter app
          flutter build linux --release
          
          # Copy required files to bundle
          BUNDLE_DIR="build/linux/x64/release/bundle"
          APP_NAME="sample_project"  # Change this to your app name
          
          # Ensure desktop file exists
          if [ -f "linux/$APP_NAME.desktop" ]; then
            cp "linux/$APP_NAME.desktop" "$BUNDLE_DIR/"
          else
            echo "[Desktop Entry]" > "$BUNDLE_DIR/$APP_NAME.desktop"
            echo "Version=1.0" >> "$BUNDLE_DIR/$APP_NAME.desktop"
            echo "Type=Application" >> "$BUNDLE_DIR/$APP_NAME.desktop"
            echo "Name=${APP_NAME^}" >> "$BUNDLE_DIR/$APP_NAME.desktop"
            echo "Exec=$APP_NAME" >> "$BUNDLE_DIR/$APP_NAME.desktop"
            echo "Icon=$APP_NAME" >> "$BUNDLE_DIR/$APP_NAME.desktop"
            echo "Comment=A Flutter application" >> "$BUNDLE_DIR/$APP_NAME.desktop"
            echo "Categories=Utility;" >> "$BUNDLE_DIR/$APP_NAME.desktop"
          fi
          
          # Copy icon if it exists
          if [ -f "linux/$APP_NAME.png" ]; then
            cp "linux/$APP_NAME.png" "$BUNDLE_DIR/"
          fi
          
          # Create AppImage
          cd "$BUNDLE_DIR"
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          ./appimagetool-x86_64.AppImage --appimage-extract
          ./squashfs-root/AppRun . ../../$APP_NAME.AppImage
          
      - name: Verify AppImage exists
        run: |
          ls -la build/linux/x64/release/
          test -f build/linux/x64/release/sample_project.AppImage || exit 1

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/linux/x64/release/sample_project.AppImage
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
