name: Flutter Linux AppImage Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux-appimage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libblkid-dev \
            liblzma-dev \
            cmake \
            ninja-build \
            pkg-config \
            clang \
            gcc \
            git \
            libfuse2
          flutter pub get

      - name: Build Linux AppImage
        run: |
          # Build the Flutter app
          flutter build linux --release
          
          # Copy the icon to the bundle if it exists
          if [ -f "linux/sample_project.png" ]; then
            cp "linux/sample_project.png" "build/linux/x64/release/bundle/"
          fi
          
          # Download and use appimagetool
          cd build/linux/x64/release/bundle
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          ./appimagetool-x86_64.AppImage --appimage-extract
          ./squashfs-root/AppRun . ../../sample_project.AppImage
          
      - name: Upload AppImage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sample_project.AppImage
          path: build/linux/x64/release/sample_project.AppImage

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/linux/x64/release/sample_project.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
