name: Flutter Linux AppImage Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux-appimage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libblkid-dev \
            liblzma-dev \
            cmake \
            ninja-build \
            pkg-config \
            clang \
            gcc \
            git \
            libfuse2
          flutter pub get

      - name: Build Linux AppImage
        run: |
          # Build the Flutter app
          flutter build linux --release
          
          # Ensure the .desktop file exists
          DESKTOP_FILE="build/linux/x64/release/bundle/$(basename $(pwd)).desktop"
          if [ ! -f "$DESKTOP_FILE" ]; then
            echo "[Desktop Entry]" > "$DESKTOP_FILE"
            echo "Version=1.0" >> "$DESKTOP_FILE"
            echo "Type=Application" >> "$DESKTOP_FILE"
            echo "Name=$(basename $(pwd))" >> "$DESKTOP_FILE"
            echo "Exec=$(basename $(pwd))" >> "$DESKTOP_FILE"
            echo "Icon=$(basename $(pwd))" >> "$DESKTOP_FILE"
            echo "Comment=Flutter Application" >> "$DESKTOP_FILE"
            echo "Categories=Utility;" >> "$DESKTOP_FILE"
          fi
          
          # Ensure the icon exists
          ICON_FILE="build/linux/x64/release/bundle/$(basename $(pwd)).png"
          if [ ! -f "$ICON_FILE" ]; then
            cp linux/$(basename $(pwd)).png "$ICON_FILE" || true
          fi
          
          # Download and use appimagetool
          cd build/linux/x64/release/bundle
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          ./appimagetool-x86_64.AppImage --appimage-extract
          ./squashfs-root/AppRun . ../../$(basename $(pwd)).AppImage
          
      - name: Upload AppImage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: my_app.AppImage
          path: build/linux/x64/release/$(basename $(pwd)).AppImage

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/linux/x64/release/$(basename $(pwd)).AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
