name: Flutter Linux AppImage Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux-appimage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libblkid-dev \
            liblzma-dev \
            cmake \
            ninja-build \
            pkg-config \
            clang \
            gcc \
            git \
            libfuse2
          flutter pub get

      - name: Build Linux AppImage
        run: |
          # Build the Flutter app
          flutter build linux --release
          
          # Copy required files to bundle
          BUNDLE_DIR="build/linux/x64/release/bundle"
          
          # Ensure desktop file exists
          if [ -f "linux/sample_project.desktop" ]; then
            cp "linux/sample_project.desktop" "$BUNDLE_DIR/"
          else
            echo "[Desktop Entry]" > "$BUNDLE_DIR/sample_project.desktop"
            echo "Version=1.0" >> "$BUNDLE_DIR/sample_project.desktop"
            echo "Type=Application" >> "$BUNDLE_DIR/sample_project.desktop"
            echo "Name=Sample Project" >> "$BUNDLE_DIR/sample_project.desktop"
            echo "Exec=sample_project" >> "$BUNDLE_DIR/sample_project.desktop"
            echo "Icon=sample_project" >> "$BUNDLE_DIR/sample_project.desktop"
            echo "Comment=A sample Flutter application" >> "$BUNDLE_DIR/sample_project.desktop"
            echo "Categories=Utility;" >> "$BUNDLE_DIR/sample_project.desktop"
          fi
          
          # Copy icon if it exists
          if [ -f "linux/sample_project.png" ]; then
            cp "linux/sample_project.png" "$BUNDLE_DIR/"
          fi
          
          # Create AppImage
          cd "$BUNDLE_DIR"
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          ./appimagetool-x86_64.AppImage --appimage-extract
          ./squashfs-root/AppRun . ../../sample_project.AppImage
          
      - name: Upload AppImage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sample_project.AppImage
          path: build/linux/x64/release/sample_project.AppImage

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/linux/x64/release/sample_project.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
